
set(GLI_PACKAGE_DIR ${PROJECT_SOURCE_DIR}/external/gli)

set(GLI_INCLUDE_DIR ${GLI_PACKAGE_DIR})
set(GLI_LIBRARY_DIR)

include_directories(${GLI_INCLUDE_DIR})

if(GLI_PACKAGE_DIR AND GLI_INCLUDE_DIR)
	set(GLI_FOUND "YES")
    MESSAGE(STATUS "GLI_INCLUDE_DIR = ${GLI_INCLUDE_DIR}")
endif(GLI_PACKAGE_DIR AND GLI_INCLUDE_DIR)